# Generated by Django 4.0.5 on 2022-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('alturaMax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('tiempoSinAgua', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('deInterior', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Abuela',
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.DeleteModel(
            name='Hijo',
        ),
        migrations.DeleteModel(
            name='Padre',
        ),
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
