# Generated by Django 4.0.5 on 2022-06-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_arbol_cactus_planta_delete_abuela_delete_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='cantidad',
        ),
    ]
