# Generated by Django 4.0.5 on 2022-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0003_remove_planta_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cactus',
            old_name='tiempoSinAgua',
            new_name='diasSinAgua',
        ),
    ]
