# Generated by Django 4.0.5 on 2022-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0004_rename_tiemposinagua_cactus_diassinagua'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('deInterior', models.CharField(max_length=40)),
            ],
        ),
    ]
