# Generated by Django 4.0.5 on 2022-07-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0005_plantaformulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbolFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('alturaMax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CactusFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombreCientifico', models.CharField(max_length=40)),
                ('diasSinAgua', models.IntegerField()),
            ],
        ),
    ]
